export enum ProgrammingLanguages {
  JavaScript = 'JavaScript',
  Python = 'Python',
  Java = 'Java',
  PHP = 'PHP',
  CPlusPlus = 'C++',
  CSharp = 'C#',
  C = 'C',
  TypeScript = 'TypeScript',
  Ruby = 'Ruby',
  Swift = 'Swift',
  Kotlin = 'Kotlin',
  Go = 'Go',
  ObjectiveC = 'Objective-C',
  R = 'R',
  MATLAB = 'MATLAB',
  Scala = 'Scala',
  Rust = 'Rust',
  Lua = 'Lua',
  Dart = 'Dart',
  Shell = 'Shell',
  Perl = 'Perl'
}
